services:
    backend:
        container_name: algoforge-backend
        restart: always
        build:
            context: .
            dockerfile: src/back/Dockerfile
        volumes:
            - ./:/app
        ports:
            - "${PORT:-5205}:3000"
        networks:
            - algo_network
        depends_on:
            - db_postgres

    db_postgres:
        image: postgres:17
        container_name: algoforge-db-postgres
        restart: always
        environment:
            POSTGRES_USER: ${DATABASE_USER:-postgres}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
            POSTGRES_DB: ${DATABASE_NAME:-postgres}
        volumes:
            - ./src/back/db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
            - db_data:/var/lib/postgresql/data
        networks:
            - algo_network
            - db_network

    pgadmin:
        image: dpage/pgadmin4:8.12
        container_name: algoforge-db-pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        ports:
            - "${PGADMIN_PORT:-5300}:80"
        networks:
            - algo_network
            - db_network
        depends_on:
            - db_postgres

volumes:
    db_data: {}

networks:
    algo_network: {}
    db_network: {}
